language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x

script:
  - bundle exec rake --trace
