language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-5.0.x
  - gemfiles/Gemfile.rails-5.1.x
  - gemfiles/Gemfile.rails-5.2.x

script:
  - bundle exec rake --trace
